const express = require("express");
const fs = require("fs/promises");
const path = require("path");
const https = require("https");
const http = require("http");

const app = express();
app.use(express.json({ limit: "1mb" }));

/* Forward JSON payload to an external URL (handles http and https) */
function forwardPayload(url, body) {
  return new Promise((resolve, reject) => {
    const data = JSON.stringify(body);
    const parsed = new URL(url);
    const mod = parsed.protocol === "https:" ? https : http;
    const req = mod.request(
      {
        hostname: parsed.hostname,
        port: parsed.port || (parsed.protocol === "https:" ? 443 : 80),
        path: parsed.pathname + parsed.search,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Content-Length": Buffer.byteLength(data),
        },
      },
      (res) => {
        let raw = "";
        res.on("data", (c) => (raw += c));
        res.on("end", () => resolve({ status: res.statusCode, body: raw }));
      }
    );
    req.on("error", reject);
    req.write(data);
    req.end();
  });
}

const dataPath = path.join(__dirname, "stats.json");

async function readData() {
  try {
    const raw = await fs.readFile(dataPath, "utf8");
    return JSON.parse(raw);
  } catch (err) {
    if (err && err.code === "ENOENT") return [];
    throw err;
  }
}

async function writeData(data) {
  await fs.writeFile(dataPath, JSON.stringify(data, null, 2));
}

/* ------------------------------------------------------------------ */
/* FPSChallenge API — fetch match config and generate matchdata.cfg   */
/* ------------------------------------------------------------------ */

const FPS_API_BASE = process.env.FPS_API_BASE || "https://fpschallenge.eu/api/v2";
const FPS_GAME = process.env.FPS_GAME || "cod1";
const MATCHDATA_PATH = process.env.MATCHDATA_PATH || path.join(__dirname, "..", "matchdata.cfg");

function fetchJSON(url) {
  return new Promise((resolve, reject) => {
    const parsed = new URL(url);
    const mod = parsed.protocol === "https:" ? https : http;
    mod.get(url, (res) => {
      let raw = "";
      res.on("data", (c) => (raw += c));
      res.on("end", () => {
        if (res.statusCode !== 200)
          return reject(new Error(`HTTP ${res.statusCode}: ${raw.slice(0, 200)}`));
        try { resolve(JSON.parse(raw)); }
        catch (e) { reject(new Error(`JSON parse error: ${e.message}`)); }
      });
    }).on("error", reject);
  });
}

function buildMatchdataCfg(data, backendPort) {
  const lines = [];
  lines.push(`// Auto-generated by cod1plus from FPSChallenge API`);
  lines.push(`// Match ${data.matchId} — ${new Date().toISOString()}`);
  lines.push(``);
  lines.push(`set cod1plus_match_id       "${data.matchId}"`);
  lines.push(`set cod1plus_start_time     "${new Date().toISOString()}"`);
  lines.push(``);
  lines.push(`set cod1plus_team1_id       "${data.team1.id}"`);
  lines.push(`set cod1plus_team1_name     "${data.team1.name}"`);
  lines.push(`set cod1plus_team1_tag      "${data.team1.tag || ""}"`);
  lines.push(`set cod1plus_team1_side     "1"`);
  lines.push(``);
  lines.push(`set cod1plus_team2_id       "${data.team2.id}"`);
  lines.push(`set cod1plus_team2_name     "${data.team2.name}"`);
  lines.push(`set cod1plus_team2_tag      "${data.team2.tag || ""}"`);
  lines.push(``);
  lines.push(`set cod1plus_format         "${data.format || "BO1"}"`);
  lines.push(`set cod1plus_mr             "MR12"`);
  lines.push(`set cod1plus_half_round     "12"`);
  lines.push(`set cod1plus_score_limit    "13"`);
  lines.push(`set cod1plus_round_limit    "24"`);
  lines.push(``);
  const mapName = Array.isArray(data.maps) && data.maps.length ? data.maps[0] : "";
  lines.push(`set cod1plus_api_url        "http://localhost:${backendPort}/api/round_end"`);
  lines.push(`set cod1plus_demo_url       ""`);
  if (mapName) lines.push(`set cod1plus_map            "${mapName}"`);
  lines.push(``);
  lines.push(`// Players`);

  let idx = 1;
  for (const p of (data.team1.players || [])) {
    lines.push(`set cod1plus_player${idx}        "${p.name},${p.uuid},1"`);
    idx++;
  }
  for (const p of (data.team2.players || [])) {
    lines.push(`set cod1plus_player${idx}        "${p.name},${p.uuid},2"`);
    idx++;
  }
  lines.push(``);
  return lines.join("\n");
}

app.get("/api/match_setup", async (req, res) => {
  try {
    const matchId = req.query.id;
    if (!matchId)
      return res.status(400).json({ ok: false, error: "Missing id parameter" });

    const apiUrl = `${FPS_API_BASE}/${FPS_GAME}/match/${matchId}`;
    console.log(`[backend] Fetching match config from ${apiUrl}`);

    const data = await fetchJSON(apiUrl);
    console.log(`[backend] Match ${data.matchId}: ${data.team1.name} vs ${data.team2.name} (${data.format})`);

    const cfg = buildMatchdataCfg(data, port);
    await fs.writeFile(MATCHDATA_PATH, cfg);
    console.log(`[backend] matchdata.cfg written to ${MATCHDATA_PATH}`);

    res.json({ ok: true, match_id: data.matchId });
  } catch (err) {
    console.error("[backend] /api/match_setup error:", err.message);
    res.status(500).json({ ok: false, error: err.message });
  }
});

app.post("/api/match_setup", async (req, res) => {
  try {
    const data = req.body || {};
    if (!data.matchId || !data.team1 || !data.team2)
      return res.status(400).json({ ok: false, error: "Missing match data" });
    const cfg = buildMatchdataCfg(data, port);
    await fs.writeFile(MATCHDATA_PATH, cfg);
    console.log(`[backend] matchdata.cfg written to ${MATCHDATA_PATH}`);
    res.json({ ok: true, match_id: data.matchId });
  } catch (err) {
    console.error("[backend] /api/match_setup error:", err.message);
    res.status(500).json({ ok: false, error: err.message });
  }
});

/* Round-end payload from cod1plus.so — store locally + forward to fpschallenge.eu */
const FPS_API_URL = process.env.FPS_API_URL || "";

app.post("/api/round_end", async (req, res) => {
  try {
    const entry = {
      received_at: new Date().toISOString(),
      payload: req.body,
    };

    /* Persist locally */
    const dataPath = path.join(__dirname, "rounds.json");
    let rounds = [];
    try { rounds = JSON.parse(await fs.readFile(dataPath, "utf8")); } catch (_) {}
    rounds.push(entry);
    await fs.writeFile(dataPath, JSON.stringify(rounds, null, 2));

    /* Forward to fpschallenge.eu if URL is configured */
    const targetUrl = FPS_API_URL || req.body._forward_url;
    if (targetUrl) {
      try {
        const fwd = await forwardPayload(targetUrl, req.body);
        console.log(`[backend] Forwarded to ${targetUrl} → ${fwd.status}: ${fwd.body.slice(0, 120)}`);
      } catch (err) {
        console.error("[backend] Forward failed:", err.message);
      }
    } else {
      console.log("[backend] No FPS_API_URL set — payload stored locally only");
    }

    res.json({ ok: true });
  } catch (err) {
    console.error("[backend] /api/round_end error:", err);
    res.status(500).json({ ok: false });
  }
});

app.get("/api/round_end", async (req, res) => {
  try {
    const dataPath = path.join(__dirname, "rounds.json");
    let rounds = [];
    try { rounds = JSON.parse(await fs.readFile(dataPath, "utf8")); } catch (_) {}
    res.json(rounds);
  } catch (err) {
    res.status(500).json({ ok: false });
  }
});

app.post("/api/stats", async (req, res) => {
  try {
    const entry = {
      received_at: new Date().toISOString(),
      payload: req.body
    };
    const data = await readData();
    data.push(entry);
    await writeData(data);
    res.json({ ok: true });
  } catch (err) {
    res.status(500).json({ ok: false });
  }
});

app.get("/api/stats", async (req, res) => {
  try {
    const data = await readData();
    res.json(data);
  } catch (err) {
    res.status(500).json({ ok: false });
  }
});

const port = Number(process.env.PORT || 3000);
app.listen(port, () => {
  process.stdout.write(`listening:${port}\n`);
});
